### ISSUE TITLE
Replace "typeclass" with "type class"

### ISSUE THREAD

**Issue by tssm** [tssm/up-to-date-real-world-haskell#3]

**Comment by bwignall** [comment]
Based on the output of `git grep -i typeclass | sed 's/using-typeclasses.org//g' | sed 's/MultiParamTypeClasses//g' | grep -i typeclass`, I believe this can be closed.

**Comment by bwignall** [comment]
@tssm do you agree that this should be closed (as fixed)?

**Comment by tssm** [comment]
Yes! Thank you so much!
